"""
Nexo Sinérgico - Pydantic Models
Data models for type safety and validation.
"""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any, Literal
from datetime import datetime
from uuid import UUID


# =====================================================
# Input Models (Frontend → Backend)
# =====================================================

class TelemetrySnapshot(BaseModel):
    """Raw telemetry data from the frontend module"""
    # Example fields - adjust based on actual module data
    demand_kw: Optional[float] = None
    cost_eur: Optional[float] = None
    efficiency_rate: Optional[float] = None
    machine_status: Optional[str] = None
    # Allow additional dynamic fields
    extra: Dict[str, Any] = Field(default_factory=dict)
    
    class Config:
        extra = "allow"  # Allow extra fields


class EngineConfig(BaseModel):
    """Configuration for how the AI should generate content"""
    audience: Literal["INVESTOR", "ENGINEER", "MARKETING"]
    style_preset: str = "CYBERPUNK_DARK"
    model_version: str = "gemini-1.5-pro"


class UserIntent(BaseModel):
    """What the user wants to achieve"""
    action: str  # e.g., "GENERATE_EXECUTIVE_REPORT", "GENERATE_EFFICIENCY_REPORT"
    target_audience: str  # e.g., "CFO_INVESTORS", "TECHNICAL_TEAM"
    tone: str = "ANALYTICAL_OPTIMISTIC"


class NexoPayload(BaseModel):
    """Complete payload sent from frontend when requesting insight generation"""
    timestamp: str
    source_module: str  # e.g., "PHOENIX_V1", "UTILITIES_V1", "VULCANO_V1"
    project_id: Optional[str] = None
    
    data_context: Dict[str, Any]  # Contains telemetry snapshot + calculated results
    user_intent: UserIntent


# =====================================================
# Output Models (Backend → Frontend)
# =====================================================

class VisualAsset(BaseModel):
    """Generated visual content"""
    type: str = "image/png"
    url: str
    alt_text: str
    prompt_used: str
    aspect_ratio: str = "16:9"


class HighlightedMetric(BaseModel):
    """KPI metric to display as a badge"""
    label: str
    value: str
    trend: Literal["positive", "negative", "neutral"] = "neutral"


class NarrativeContent(BaseModel):
    """Text-based narrative generated by AI"""
    headline: str
    sub_headline: str
    body_markdown: str
    call_to_action: Optional[str] = None
    highlighted_metrics: List[HighlightedMetric] = Field(default_factory=list)


class UIHints(BaseModel):
    """Visual styling hints for the frontend"""
    theme_mode: str = "dark_cyberpunk"
    primary_color_hex: str = "#00D4FF"
    secondary_color_hex: str = "#FFC107"
    card_border_style: str = "glowing_cyan"
    icon: str = "lightning-bolt-shield"


class Action(BaseModel):
    """Available actions the user can take"""
    id: str
    label: str
    icon: str


class InsightCardResponse(BaseModel):
    """Complete response returned to frontend"""
    request_id: str
    timestamp: str
    status: str = "success"
    generated_for_role: str
    
    visual_asset: VisualAsset
    narrative_content: NarrativeContent
    ui_hints: UIHints
    available_actions: List[Action] = Field(default_factory=list)


# =====================================================
# Database Models
# =====================================================

class AIGeneration(BaseModel):
    """Database model for ai_generations table"""
    id: Optional[UUID] = None
    project_id: Optional[UUID] = None
    parent_generation_id: Optional[UUID] = None
    iteration_index: int = 1
    
    telemetry_snapshot: Dict[str, Any]
    engine_config: Dict[str, Any]
    
    full_prompt_text: str
    negative_prompt_text: Optional[str] = None
    
    output_url: Optional[str] = None
    output_metadata: Optional[Dict[str, Any]] = None
    
    narrative_headline: Optional[str] = None
    narrative_sub_headline: Optional[str] = None
    narrative_body_markdown: Optional[str] = None
    
    status: str = "PENDING"
    error_message: Optional[str] = None
    
    created_at: Optional[datetime] = None


class AIFeedback(BaseModel):
    """Database model for ai_feedback table"""
    id: Optional[UUID] = None
    generation_id: UUID
    
    sentiment: Literal[-1, 0, 1]
    tags: List[str] = Field(default_factory=list)
    user_comment: Optional[str] = None
    action_taken: Optional[str] = None
    user_id: Optional[UUID] = None
    
    created_at: Optional[datetime] = None
